"""remove default role

Revision ID: 779903bde63f
Revises: f33afb741b14
Create Date: 2025-01-30 21:19:43.762078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779903bde63f'
down_revision: Union[str, None] = 'f33afb741b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_department', table_name='sales')
    op.drop_index('ix_sales_year', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_name', 'users', ['name'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('sales', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('year', 'department')
    )
    op.create_index('ix_sales_year', 'sales', ['year'], unique=False)
    op.create_index('ix_sales_department', 'sales', ['department'], unique=False)
    # ### end Alembic commands ###
